const dairyProducts = [
     {
          id: 1,
          name: "Organic Whole Milk",
          type: "Whole Milk",
          category: "Milk",
          image: 'https://pravarshaindustries.com/storage/products/6PDp0ncKeSEepO3e0nsSRlJgIAs1J63uthp5RPkt.webp',
          description: "Fresh and organic whole milk from grass-fed cows.",
          price: 3.99,
          nutrition_info: {
               calories: 150,
               fat: "8g",
               protein: "8g",
               carbohydrates: "12g",
               sugar: "12g",
               calcium: "300mg",
               vitamin_d: "2.5mcg",
          },
          brand: "FarmFresh",
          size: "1L",
          expiration_date: "2024-10-10",
          availability: "In Stock",
          deliveryMessage: 'Delivered in 10min',
          additionalImages: [
               'https://pravarshaindustries.com/storage/products/6PDp0ncKeSEepO3e0nsSRlJgIAs1J63uthp5RPkt.webp',
               'https://pravarshaindustries.com/storage/products/iC7OTkjbSpRdMjMHMRHtvHNWBcwOMEbFO6Ni24qU.webp',
               'https://pravarshaindustries.com/storage/products/QcVhV04lcX2gRwl3I9qrzzluYGDpbG6C6cbdbAG5.webp',
               'https://pravarshaindustries.com/storage/products/IFX5zJrNaWTBnXrlELtp0mOlJwgTsKNNAz3KHzkc.png'
             ],
     },
     {
          id: 2,
          name: "Almond Milk",
          type: "Plant-Based Milk",
          category: "Milk",
          image: 'https://pravarshaindustries.com/storage/products/Z2fYDKhCjLWdUslneLGpYZZxc8xY3HuRDzEqiNFP.png',
          description:
               "Smooth almond milk, perfect for lactose-intolerant consumers.",
          price: 4.49,
          nutrition_info: {
               calories: 60,
               fat: "2.5g",
               protein: "1g",
               carbohydrates: "8g",
               sugar: "7g",
               calcium: "450mg",
               vitamin_d: "2.5mcg",
          },
          brand: "NuttyDelight",
          size: "1L",
          expiration_date: "2024-11-05",
          availability: "In Stock",
          deliveryMessage: 'Delivered in 10min',
          additionalImages: [
               'https://pravarshaindustries.com/storage/products/6PDp0ncKeSEepO3e0nsSRlJgIAs1J63uthp5RPkt.webp',
               'https://pravarshaindustries.com/storage/products/iC7OTkjbSpRdMjMHMRHtvHNWBcwOMEbFO6Ni24qU.webp',
               'https://pravarshaindustries.com/storage/products/QcVhV04lcX2gRwl3I9qrzzluYGDpbG6C6cbdbAG5.webp',
               'https://pravarshaindustries.com/storage/products/IFX5zJrNaWTBnXrlELtp0mOlJwgTsKNNAz3KHzkc.png'
             ],
     },
     {
          id: 3,
          name: "Skimmed Milk",
          type: "Skim Milk",
          category: "Milk",
          image: 'https://pravarshaindustries.com/storage/products/6PDp0ncKeSEepO3e0nsSRlJgIAs1J63uthp5RPkt.webp',
          description: "Low-fat skimmed milk for a healthier diet option.",
          price: 2.99,
          nutrition_info: {
               calories: 90,
               fat: "0g",
               protein: "8g",
               carbohydrates: "12g",
               sugar: "12g",
               calcium: "300mg",
               vitamin_d: "2.5mcg",
          },
          brand: "HealthyMoo",
          size: "1L",
          expiration_date: "2024-10-20",
          availability: "In Stock",
          deliveryMessage: 'Delivered in 10min',
          additionalImages: [
               'https://pravarshaindustries.com/storage/products/6PDp0ncKeSEepO3e0nsSRlJgIAs1J63uthp5RPkt.webp',
               'https://pravarshaindustries.com/storage/products/iC7OTkjbSpRdMjMHMRHtvHNWBcwOMEbFO6Ni24qU.webp',
               'https://pravarshaindustries.com/storage/products/QcVhV04lcX2gRwl3I9qrzzluYGDpbG6C6cbdbAG5.webp',
               'https://pravarshaindustries.com/storage/products/IFX5zJrNaWTBnXrlELtp0mOlJwgTsKNNAz3KHzkc.png'
             ],
     },
     {
          id: 4,
          name: "Heavy Whipping Cream",
          type: "Cream",
          category: "Cream",
          image: 'https://pravarshaindustries.com/storage/products/Z2fYDKhCjLWdUslneLGpYZZxc8xY3HuRDzEqiNFP.png',
          description: "Rich and creamy, perfect for desserts and sauces.",
          price: 5.49,
          nutrition_info: {
               calories: 400,
               fat: "40g",
               protein: "3g",
               carbohydrates: "3g",
               sugar: "2g",
               calcium: "80mg",
               vitamin_d: "1mcg",
          },
          brand: "CreamyDream",
          size: "500ml",
          expiration_date: "2024-09-30",
          availability: "In Stock",
          deliveryMessage: 'Delivered in 10min',
          additionalImages: [
               'https://pravarshaindustries.com/storage/products/6PDp0ncKeSEepO3e0nsSRlJgIAs1J63uthp5RPkt.webp',
               'https://pravarshaindustries.com/storage/products/iC7OTkjbSpRdMjMHMRHtvHNWBcwOMEbFO6Ni24qU.webp',
               'https://pravarshaindustries.com/storage/products/QcVhV04lcX2gRwl3I9qrzzluYGDpbG6C6cbdbAG5.webp',
               'https://pravarshaindustries.com/storage/products/IFX5zJrNaWTBnXrlELtp0mOlJwgTsKNNAz3KHzkc.png'
             ],
     },
     {
          id: 5,
          name: "Sour Cream",
          type: "Cultured Cream",
          category: "Cream",
          image: 'https://pravarshaindustries.com/storage/products/DXlyMp8QjknwdY06EWYxvs0BgpHM4f8khlXvtUVl.png',
          description: "Tangy sour cream, great for dips and toppings.",
          price: 3.99,
          nutrition_info: {
               calories: 200,
               fat: "20g",
               protein: "2g",
               carbohydrates: "5g",
               sugar: "3g",
               calcium: "100mg",
               vitamin_d: "0.5mcg",
          },
          brand: "TangyTaste",
          size: "250g",
          expiration_date: "2024-09-18",
          availability: "In Stock",
          deliveryMessage: 'Delivered in 10min',
          additionalImages: [
               'https://pravarshaindustries.com/storage/products/6PDp0ncKeSEepO3e0nsSRlJgIAs1J63uthp5RPkt.webp',
               'https://pravarshaindustries.com/storage/products/iC7OTkjbSpRdMjMHMRHtvHNWBcwOMEbFO6Ni24qU.webp',
               'https://pravarshaindustries.com/storage/products/QcVhV04lcX2gRwl3I9qrzzluYGDpbG6C6cbdbAG5.webp',
               'https://pravarshaindustries.com/storage/products/IFX5zJrNaWTBnXrlELtp0mOlJwgTsKNNAz3KHzkc.png'
             ],
     },
     {
          id: 6,
          name: "Half & Half Cream",
          type: "Light Cream",
          category: "Cream",
          image: 'https://pravarshaindustries.com/storage/products/DXlyMp8QjknwdY06EWYxvs0BgpHM4f8khlXvtUVl.png',
          description: "Light cream, ideal for coffee and light desserts.",
          price: 2.99,
          nutrition_info: {
               calories: 120,
               fat: "10g",
               protein: "2g",
               carbohydrates: "5g",
               sugar: "4g",
               calcium: "80mg",
               vitamin_d: "0.5mcg",
          },
          brand: "MorningBrew",
          size: "500ml",
          expiration_date: "2024-10-05",
          availability: "In Stock",
          deliveryMessage: 'Delivered in 10min',
          additionalImages: [
               'https://pravarshaindustries.com/storage/products/6PDp0ncKeSEepO3e0nsSRlJgIAs1J63uthp5RPkt.webp',
               'https://pravarshaindustries.com/storage/products/iC7OTkjbSpRdMjMHMRHtvHNWBcwOMEbFO6Ni24qU.webp',
               'https://pravarshaindustries.com/storage/products/QcVhV04lcX2gRwl3I9qrzzluYGDpbG6C6cbdbAG5.webp',
               'https://pravarshaindustries.com/storage/products/IFX5zJrNaWTBnXrlELtp0mOlJwgTsKNNAz3KHzkc.png'
             ],
     },
     {
          id: 7,
          name: "Greek Yogurt",
          type: "Yogurt",
          category: "Curd",
          image: 'https://pravarshaindustries.com/storage/products/jDr8YKq3ek0mmXT3JdWohOqCkcemMRNYYv3N7UVG.webp',
          description: "Thick and creamy Greek yogurt rich in probiotics.",
          price: 2.49,
          nutrition_info: {
               calories: 100,
               fat: "0g",
               protein: "10g",
               carbohydrates: "7g",
               sugar: "5g",
               calcium: "200mg",
               vitamin_d: "1.5mcg",
          },
          brand: "YogurtCo",
          size: "200g",
          expiration_date: "2024-09-25",
          availability: "In Stock",
          deliveryMessage: 'Delivered in 10min',
          additionalImages: [
               'https://pravarshaindustries.com/storage/products/6PDp0ncKeSEepO3e0nsSRlJgIAs1J63uthp5RPkt.webp',
               'https://pravarshaindustries.com/storage/products/iC7OTkjbSpRdMjMHMRHtvHNWBcwOMEbFO6Ni24qU.webp',
               'https://pravarshaindustries.com/storage/products/QcVhV04lcX2gRwl3I9qrzzluYGDpbG6C6cbdbAG5.webp',
               'https://pravarshaindustries.com/storage/products/IFX5zJrNaWTBnXrlELtp0mOlJwgTsKNNAz3KHzkc.png'
             ],
     },
     {
          id: 8,
          name: "Probiotic Curd",
          type: "Curd",
          category: "Curd",
          image: 'https://pravarshaindustries.com/storage/products/jDr8YKq3ek0mmXT3JdWohOqCkcemMRNYYv3N7UVG.webp',
          description:
               "Fresh curd enriched with natural probiotics for gut health.",
          price: 1.99,
          nutrition_info: {
               calories: 80,
               fat: "3g",
               protein: "5g",
               carbohydrates: "6g",
               sugar: "4g",
               calcium: "150mg",
               vitamin_d: "1mcg",
          },
          brand: "GutGood",
          size: "250g",
          expiration_date: "2024-09-28",
          availability: "In Stock",
          deliveryMessage: 'Delivered in 10min',
          additionalImages: [
               'https://pravarshaindustries.com/storage/products/6PDp0ncKeSEepO3e0nsSRlJgIAs1J63uthp5RPkt.webp',
               'https://pravarshaindustries.com/storage/products/iC7OTkjbSpRdMjMHMRHtvHNWBcwOMEbFO6Ni24qU.webp',
               'https://pravarshaindustries.com/storage/products/QcVhV04lcX2gRwl3I9qrzzluYGDpbG6C6cbdbAG5.webp',
               'https://pravarshaindustries.com/storage/products/IFX5zJrNaWTBnXrlELtp0mOlJwgTsKNNAz3KHzkc.png'
             ],
     },
     {
          id: 9,
          name: "Low-Fat Yogurt",
          type: "Yogurt",
          category: "Curd",
          image: 'https://pravarshaindustries.com/storage/products/jDr8YKq3ek0mmXT3JdWohOqCkcemMRNYYv3N7UVG.webp',
          description:
               "Delicious low-fat yogurt, a healthy choice for everyday use.",
          price: 2.29,
          nutrition_info: {
               calories: 90,
               fat: "1g",
               protein: "9g",
               carbohydrates: "10g",
               sugar: "8g",
               calcium: "200mg",
               vitamin_d: "1mcg",
          },
          brand: "HealthyChoice",
          size: "200g",
          expiration_date: "2024-10-01",
          availability: "In Stock",
          deliveryMessage: 'Delivered in 10min',
          additionalImages: [
               'https://pravarshaindustries.com/storage/products/6PDp0ncKeSEepO3e0nsSRlJgIAs1J63uthp5RPkt.webp',
               'https://pravarshaindustries.com/storage/products/iC7OTkjbSpRdMjMHMRHtvHNWBcwOMEbFO6Ni24qU.webp',
               'https://pravarshaindustries.com/storage/products/QcVhV04lcX2gRwl3I9qrzzluYGDpbG6C6cbdbAG5.webp',
               'https://pravarshaindustries.com/storage/products/IFX5zJrNaWTBnXrlELtp0mOlJwgTsKNNAz3KHzkc.png'
             ],
     },
     {
          id: 10,
          name: "Fresh Paneer",
          type: "Paneer",
          category: "Paneer",
          image: 'https://pravarshaindustries.com/storage/products/0sHPo3oXQQBJDLXNt4d74gujcAkzCchtpYM4ITJ6.webp',
          description: "Soft and fresh paneer, perfect for Indian dishes.",
          price: 4.99,
          nutrition_info: {
               calories: 250,
               fat: "20g",
               protein: "15g",
               carbohydrates: "4g",
               sugar: "3g",
               calcium: "300mg",
               vitamin_d: "0mcg",
          },
          brand: "IndianKitchen",
          size: "500g",
          expiration_date: "2024-10-08",
          availability: "In Stock",
          deliveryMessage: 'Delivered in 10min',
          additionalImages: [
               'https://pravarshaindustries.com/storage/products/6PDp0ncKeSEepO3e0nsSRlJgIAs1J63uthp5RPkt.webp',
               'https://pravarshaindustries.com/storage/products/iC7OTkjbSpRdMjMHMRHtvHNWBcwOMEbFO6Ni24qU.webp',
               'https://pravarshaindustries.com/storage/products/QcVhV04lcX2gRwl3I9qrzzluYGDpbG6C6cbdbAG5.webp',
               'https://pravarshaindustries.com/storage/products/IFX5zJrNaWTBnXrlELtp0mOlJwgTsKNNAz3KHzkc.png'
             ],
     },
     {
          id: 11,
          name: "Low-Fat Paneer",
          type: "Paneer",
          category: "Paneer",
          image: 'https://pravarshaindustries.com/storage/products/0sHPo3oXQQBJDLXNt4d74gujcAkzCchtpYM4ITJ6.webp',
          description: "Low-fat paneer for a healthy and nutritious meal.",
          price: 5.49,
          nutrition_info: {
               calories: 180,
               fat: "10g",
               protein: "20g",
               carbohydrates: "2g",
               sugar: "2g",
               calcium: "300mg",
               vitamin_d: "0mcg",
          },
          brand: "HealthLite",
          size: "400g",
          expiration_date: "2024-10-12",
          availability: "In Stock",
          deliveryMessage: 'Delivered in 10min',
          additionalImages: [
               'https://pravarshaindustries.com/storage/products/6PDp0ncKeSEepO3e0nsSRlJgIAs1J63uthp5RPkt.webp',
               'https://pravarshaindustries.com/storage/products/iC7OTkjbSpRdMjMHMRHtvHNWBcwOMEbFO6Ni24qU.webp',
               'https://pravarshaindustries.com/storage/products/QcVhV04lcX2gRwl3I9qrzzluYGDpbG6C6cbdbAG5.webp',
               'https://pravarshaindustries.com/storage/products/IFX5zJrNaWTBnXrlELtp0mOlJwgTsKNNAz3KHzkc.png'
             ],
     },
     {
          id: 12,
          name: "Marinated Paneer Cubes",
          type: "Paneer",
          category: "Paneer",
          image: 'https://pravarshaindustries.com/storage/products/0sHPo3oXQQBJDLXNt4d74gujcAkzCchtpYM4ITJ6.webp',
          description: "Ready-to-cook marinated paneer cubes with spices.",
          price: 6.99,
          nutrition_info: {
               calories: 220,
               fat: "15g",
               protein: "18g",
               carbohydrates: "5g",
               sugar: "3g",
               calcium: "250mg",
               vitamin_d: "0mcg",
          },
          brand: "SpiceReady",
          size: "300g",
          expiration_date: "2024-10-15",
          availability: "In Stock",
          deliveryMessage: 'Delivered in 10min',
          additionalImages: [
               'https://pravarshaindustries.com/storage/products/6PDp0ncKeSEepO3e0nsSRlJgIAs1J63uthp5RPkt.webp',
               'https://pravarshaindustries.com/storage/products/iC7OTkjbSpRdMjMHMRHtvHNWBcwOMEbFO6Ni24qU.webp',
               'https://pravarshaindustries.com/storage/products/QcVhV04lcX2gRwl3I9qrzzluYGDpbG6C6cbdbAG5.webp',
               'https://pravarshaindustries.com/storage/products/IFX5zJrNaWTBnXrlELtp0mOlJwgTsKNNAz3KHzkc.png'
             ],
     },
     {
          id: 13,
          name: "Pure Cow Ghee",
          type: "Ghee",
          category: "Ghee",
          image: 'https://pravarshaindustries.com/storage/products/VSe5rdE5o5ARwyM5qQR224H1v12OaFMIyUrarEjx.png',
          description:
               "Rich and aromatic pure cow ghee, ideal for cooking and desserts.",
          price: 12.99,
          nutrition_info: {
               calories: 120,
               fat: "14g",
               protein: "0g",
               carbohydrates: "0g",
               sugar: "0g",
               calcium: "0mg",
               vitamin_d: "0.2mcg",
          },
          brand: "DesiGhee",
          size: "500ml",
          expiration_date: "2025-01-01",
          availability: "In Stock",
          deliveryMessage: 'Delivered in 10min',
          additionalImages: [
               'https://pravarshaindustries.com/storage/products/6PDp0ncKeSEepO3e0nsSRlJgIAs1J63uthp5RPkt.webp',
               'https://pravarshaindustries.com/storage/products/iC7OTkjbSpRdMjMHMRHtvHNWBcwOMEbFO6Ni24qU.webp',
               'https://pravarshaindustries.com/storage/products/QcVhV04lcX2gRwl3I9qrzzluYGDpbG6C6cbdbAG5.webp',
               'https://pravarshaindustries.com/storage/products/IFX5zJrNaWTBnXrlELtp0mOlJwgTsKNNAz3KHzkc.png'
             ],
     },
     {
          id: 14,
          name: "Organic Ghee",
          type: "Ghee",
          category: "Ghee",
          image: 'https://pravarshaindustries.com/storage/products/VSe5rdE5o5ARwyM5qQR224H1v12OaFMIyUrarEjx.png',
          description: "Organic ghee made from the milk of grass-fed cows.",
          price: 14.99,
          nutrition_info: {
               calories: 120,
               fat: "14g",
               protein: "0g",
               carbohydrates: "0g",
               sugar: "0g",
               calcium: "0mg",
               vitamin_d: "0.3mcg",
          },
          brand: "NaturePure",
          size: "500ml",
          expiration_date: "2025-01-15",
          availability: "In Stock",
          deliveryMessage: 'Delivered in 10min',
          additionalImages: [
               'https://pravarshaindustries.com/storage/products/6PDp0ncKeSEepO3e0nsSRlJgIAs1J63uthp5RPkt.webp',
               'https://pravarshaindustries.com/storage/products/iC7OTkjbSpRdMjMHMRHtvHNWBcwOMEbFO6Ni24qU.webp',
               'https://pravarshaindustries.com/storage/products/QcVhV04lcX2gRwl3I9qrzzluYGDpbG6C6cbdbAG5.webp',
               'https://pravarshaindustries.com/storage/products/IFX5zJrNaWTBnXrlELtp0mOlJwgTsKNNAz3KHzkc.png'
             ],
     },
     {
          id: 15,
          name: "Herbal Infused Ghee",
          type: "Ghee",
          category: "Ghee",
          image: 'https://pravarshaindustries.com/storage/products/VSe5rdE5o5ARwyM5qQR224H1v12OaFMIyUrarEjx.png',
          description: "Ghee infused with herbs for a healthy twist.",
          price: 15.99,
          nutrition_info: {
               calories: 130,
               fat: "15g",
               protein: "0g",
               carbohydrates: "0g",
               sugar: "0g",
               calcium: "0mg",
               vitamin_d: "0.4mcg",
          },
          brand: "AyurvedaGold",
          size: "500ml",
          expiration_date: "2025-02-01",
          availability: "In Stock",
          deliveryMessage: 'Delivered in 10min',
          additionalImages: [
               'https://pravarshaindustries.com/storage/products/6PDp0ncKeSEepO3e0nsSRlJgIAs1J63uthp5RPkt.webp',
               'https://pravarshaindustries.com/storage/products/iC7OTkjbSpRdMjMHMRHtvHNWBcwOMEbFO6Ni24qU.webp',
               'https://pravarshaindustries.com/storage/products/QcVhV04lcX2gRwl3I9qrzzluYGDpbG6C6cbdbAG5.webp',
               'https://pravarshaindustries.com/storage/products/IFX5zJrNaWTBnXrlELtp0mOlJwgTsKNNAz3KHzkc.png'
             ],
     },
     {
          id: 16,
          name: "Traditional Buttermilk",
          type: "Buttermilk",
          category: "Buttermilk",
          image: 'https://pravarshaindustries.com/storage/products/iGRNteTpUdrwY4tTTJyyiWO7VHaB8KetymECzPqx.png',
          description: "Refreshing traditional buttermilk with a tangy flavor.",
          price: 1.49,
          nutrition_info: {
               calories: 50,
               fat: "2g",
               protein: "4g",
               carbohydrates: "5g",
               sugar: "4g",
               calcium: "120mg",
               vitamin_d: "0.5mcg",
          },
          brand: "CoolSip",
          size: "300ml",
          expiration_date: "2024-09-20",
          availability: "In Stock",
          deliveryMessage: 'Delivered in 10min',
          additionalImages: [
               'https://pravarshaindustries.com/storage/products/6PDp0ncKeSEepO3e0nsSRlJgIAs1J63uthp5RPkt.webp',
               'https://pravarshaindustries.com/storage/products/iC7OTkjbSpRdMjMHMRHtvHNWBcwOMEbFO6Ni24qU.webp',
               'https://pravarshaindustries.com/storage/products/QcVhV04lcX2gRwl3I9qrzzluYGDpbG6C6cbdbAG5.webp',
               'https://pravarshaindustries.com/storage/products/IFX5zJrNaWTBnXrlELtp0mOlJwgTsKNNAz3KHzkc.png'
             ],
     },
     {
          id: 17,
          name: "Masala Buttermilk",
          type: "Buttermilk",
          category: "Buttermilk",
          image: 'https://pravarshaindustries.com/storage/products/iGRNteTpUdrwY4tTTJyyiWO7VHaB8KetymECzPqx.png',
          description: "Spiced buttermilk with a mix of Indian spices.",
          price: 1.99,
          nutrition_info: {
               calories: 55,
               fat: "2g",
               protein: "4g",
               carbohydrates: "6g",
               sugar: "4g",
               calcium: "130mg",
               vitamin_d: "0.6mcg",
          },
          brand: "SpicySip",
          size: "300ml",
          expiration_date: "2024-09-22",
          availability: "In Stock",
          deliveryMessage: 'Delivered in 10min',
          additionalImages: [
               'https://pravarshaindustries.com/storage/products/6PDp0ncKeSEepO3e0nsSRlJgIAs1J63uthp5RPkt.webp',
               'https://pravarshaindustries.com/storage/products/iC7OTkjbSpRdMjMHMRHtvHNWBcwOMEbFO6Ni24qU.webp',
               'https://pravarshaindustries.com/storage/products/QcVhV04lcX2gRwl3I9qrzzluYGDpbG6C6cbdbAG5.webp',
               'https://pravarshaindustries.com/storage/products/IFX5zJrNaWTBnXrlELtp0mOlJwgTsKNNAz3KHzkc.png'
             ],
     },
     {
          id: 18,
          name: "Low-Fat Buttermilk",
          type: "Buttermilk",
          category: "Buttermilk",
          image: 'https://pravarshaindustries.com/storage/products/iGRNteTpUdrwY4tTTJyyiWO7VHaB8KetymECzPqx.png',
          description: "Low-fat buttermilk for a healthier option.",
          price: 1.69,
          nutrition_info: {
               calories: 40,
               fat: "1g",
               protein: "4g",
               carbohydrates: "4g",
               sugar: "3g",
               calcium: "110mg",
               vitamin_d: "0.4mcg",
          },
          brand: "HealthSip",
          size: "300ml",
          expiration_date: "2024-09-18",
          availability: "In Stock",
          deliveryMessage: 'Delivered in 10min',
          additionalImages: [
               'https://pravarshaindustries.com/storage/products/6PDp0ncKeSEepO3e0nsSRlJgIAs1J63uthp5RPkt.webp',
               'https://pravarshaindustries.com/storage/products/iC7OTkjbSpRdMjMHMRHtvHNWBcwOMEbFO6Ni24qU.webp',
               'https://pravarshaindustries.com/storage/products/QcVhV04lcX2gRwl3I9qrzzluYGDpbG6C6cbdbAG5.webp',
               'https://pravarshaindustries.com/storage/products/IFX5zJrNaWTBnXrlELtp0mOlJwgTsKNNAz3KHzkc.png'
             ],
     },
];

export default dairyProducts;
